before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: HF15V32Wl0OeltcWFKToT6KPjvL1bn88RIGfbWBYuj1IEkNLEIhi5e9VQZqG2CgsMjhx1XsIVFja7OJT6LCOBKaGGDyq87nEeCotzs6C+lWQ1Lx+dm/A7vGRFnLbpmqz/IJVll+l3HHfq+NfaqTMY1LFas6xFArpp/MAfbS4UfTo6QG0Mig1BzUhBCH954rm++bslQb60pyjgpYR9YPL0scVfVB88DmsRBDVoU+ZjZYBqHswtwYUmCXrhtVOVlh2xMSMNpTnK2eCmJtbxNPFNDv1MYPYalUWbPPEXKnWAKkS1RUVJKVFbhhu/IBZP0ATbxP9rYlBwtGNFL301OXL/kbnH+IgBomuUNkSCVYB6CPlj7ZmiaJwjPP2yH59XIelwxkowFduVuMlC2qkjpg3gXTl1O3RAInbWr3EgVQ2Kwm11u+HD823xBDJfS/oYuH3lIsGKhApMV+QwQYYRfQcy5I0poKGL/Bs+gNRS3HgMsleLqpgotUM2u26OSx3ZY2nPUJtgAsz0LPBEhGEgTo0+2mqDb2+cUA65+OPly8dk+YEoK9T1J1UDZ3vYEwsn6n32oU1bP6OXeHBdbWB/61XWqgvGJQ55vKp6ThPOy1QnKL9HeXBaqoyZ6HVPrv+Ufg2v+9oA4OYxw37g0C2e5dkgIOHy5vrBz3+QSIwzT9CdZ0= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
